const data = {
  last_update: "2024-04-01",
  total_province: 34,
  provinces: [
    {
      kota: "Jakarta",
      kasus: 10,
      sembuh: 5,
      meninggal: 3,
      dirawat: 8,
    },
    {
      kota: "Jawa Barat",
      kasus: 20,
      sembuh: 15,
      meninggal: 10,
      dirawat: 12,
    },
    {
      kota: "Jawa Tengah",
      kasus: 15,
      sembuh: 8,
      meninggal: 6,
      dirawat: 9,
    },
    {
      kota: "Jawa Timur",
      kasus: 25,
      sembuh: 18,
      meninggal: 12,
      dirawat: 18,
    },
    {
      kota: "Banten",
      kasus: 30,
      sembuh: 20,
      meninggal: 15,
      dirawat: 25,
    },
    {
      kota: "Yogyakarta",
      kasus: 12,
      sembuh: 6,
      meninggal: 4,
      dirawat: 9,
    },
    {
      kota: "Kalimantan Timur",
      kasus: 28,
      sembuh: 14,
      meninggal: 10,
      dirawat: 16,
    },
    {
      kota: "Bali",
      kasus: 35,
      sembuh: 20,
      meninggal: 15,
      dirawat: 22,
    },
    {
      kota: "Sumatera Utara",
      kasus: 40,
      sembuh: 25,
      meninggal: 18,
      dirawat: 23,
    },
    {
      kota: "Riau",
      kasus: 45,
      sembuh: 30,
      meninggal: 20,
      dirawat: 25,
    },
    {
      kota: "Sulawesi Selatan",
      kasus: 38,
      sembuh: 22,
      meninggal: 16,
      dirawat: 24,
    },
    {
      kota: "Sumatera Barat",
      kasus: 50,
      sembuh: 35,
      meninggal: 25,
      dirawat: 30,
    },
    {
      kota: "Nusa Tenggara Timur",
      kasus: 55,
      sembuh: 40,
      meninggal: 28,
      dirawat: 35,
    },
    {
      kota: "Kalimantan Selatan",
      kasus: 60,
      sembuh: 45,
      meninggal: 30,
      dirawat: 40,
    },
    {
      kota: "Sumatera Selatan",
      kasus: 65,
      sembuh: 50,
      meninggal: 35,
      dirawat: 45,
    },
    {
      kota: "Lampung",
      kasus: 70,
      sembuh: 55,
      meninggal: 40,
      dirawat: 50,
    },
    {
      kota: "Kepulauan Riau",
      kasus: 75,
      sembuh: 60,
      meninggal: 45,
      dirawat: 55,
    },
    {
      kota: "Bangka Belitung",
      kasus: 80,
      sembuh: 65,
      meninggal: 50,
      dirawat: 60,
    },
    {
      kota: "Kalimantan Barat",
      kasus: 85,
      sembuh: 70,
      meninggal: 55,
      dirawat: 65,
    },
    {
      kota: "Sulawesi Tengah",
      kasus: 90,
      sembuh: 75,
      meninggal: 60,
      dirawat: 70,
    },
    {
      kota: "Kalimantan Tengah",
      kasus: 95,
      sembuh: 80,
      meninggal: 65,
      dirawat: 75,
    },
    {
      kota: "Sulawesi Utara",
      kasus: 100,
      sembuh: 85,
      meninggal: 70,
      dirawat: 80,
    },
    {
      kota: "Papua",
      kasus: 105,
      sembuh: 90,
      meninggal: 75,
      dirawat: 85,
    },
    {
      kota: "Kalimantan Utara",
      kasus: 110,
      sembuh: 95,
      meninggal: 80,
      dirawat: 90,
    },
    {
      kota: "Aceh",
      kasus: 115,
      sembuh: 100,
      meninggal: 85,
      dirawat: 95,
    },
    {
      kota: "Jambi",
      kasus: 120,
      sembuh: 105,
      meninggal: 90,
      dirawat: 100,
    },
    {
      kota: "Nusa Tenggara Barat",
      kasus: 125,
      sembuh: 110,
      meninggal: 95,
      dirawat: 105,
    },
    {
      kota: "Papua Barat",
      kasus: 130,
      sembuh: 115,
      meninggal: 100,
      dirawat: 110,
    },
    {
      kota: "Bengkulu",
      kasus: 135,
      sembuh: 120,
      meninggal: 105,
      dirawat: 115,
    },
    {
      kota: "Sulawesi Tenggara",
      kasus: 140,
      sembuh: 125,
      meninggal: 110,
      dirawat: 120,
    },
    {
      kota: "Maluku",
      kasus: 145,
      sembuh: 130,
      meninggal: 115,
      dirawat: 125,
    },
    {
      kota: "Sulawesi Barat",
      kasus: 150,
      sembuh: 135,
      meninggal: 120,
      dirawat: 130,
    },
    {
      kota: "Maluku Utara",
      kasus: 155,
      sembuh: 140,
      meninggal: 125,
      dirawat: 135,
    },
    {
      kota: "Gorontalo",
      kasus: 160,
      sembuh: 145,
      meninggal: 130,
      dirawat: 140,
    },
  ],
}
export default data;