const data = {
  last_update: "2024-04-01",
  total_province: 34,
  provinces: [
    {
      name: "Jakarta",
      confirmed: 10,
      recovered: 5,
      death: 3,
      treatment: 8,
    },
    {
      name: "Jawa Barat",
      confirmed: 20,
      recovered: 15,
      death: 10,
      treatment: 12,
    },
    {
      name: "Jawa Tengah",
      confirmed: 15,
      recovered: 8,
      death: 6,
      treatment: 9,
    },
    {
      name: "Jawa Timur",
      confirmed: 25,
      recovered: 18,
      death: 12,
      treatment: 18,
    },
    {
      name: "Banten",
      confirmed: 30,
      recovered: 20,
      death: 15,
      treatment: 25,
    },
    {
      name: "Yogyakarta",
      confirmed: 12,
      recovered: 6,
      death: 4,
      treatment: 9,
    },
    {
      name: "Kalimantan Timur",
      confirmed: 28,
      recovered: 14,
      death: 10,
      treatment: 16,
    },
    {
      name: "Bali",
      confirmed: 35,
      recovered: 20,
      death: 15,
      treatment: 22,
    },
    {
      name: "Sumatera Utara",
      confirmed: 40,
      recovered: 25,
      death: 18,
      treatment: 23,
    },
    {
      name: "Riau",
      confirmed: 45,
      recovered: 30,
      death: 20,
      treatment: 25,
    },
    {
      name: "Sulawesi Selatan",
      confirmed: 38,
      recovered: 22,
      death: 16,
      treatment: 24,
    },
    {
      name: "Sumatera Barat",
      confirmed: 50,
      recovered: 35,
      death: 25,
      treatment: 30,
    },
    {
      name: "Nusa Tenggara Timur",
      confirmed: 55,
      recovered: 40,
      death: 28,
      treatment: 35,
    },
    {
      name: "Kalimantan Selatan",
      confirmed: 60,
      recovered: 45,
      death: 30,
      treatment: 40,
    },
    {
      name: "Sumatera Selatan",
      confirmed: 65,
      recovered: 50,
      death: 35,
      treatment: 45,
    },
    {
      name: "Lampung",
      confirmed: 70,
      recovered: 55,
      death: 40,
      treatment: 50,
    },
    {
      name: "Kepulauan Riau",
      confirmed: 75,
      recovered: 60,
      death: 45,
      treatment: 55,
    },
    {
      name: "Bangka Belitung",
      confirmed: 80,
      recovered: 65,
      death: 50,
      treatment: 60,
    },
    {
      name: "Kalimantan Barat",
      confirmed: 85,
      recovered: 70,
      death: 55,
      treatment: 65,
    },
    {
      name: "Sulawesi Tengah",
      confirmed: 90,
      recovered: 75,
      death: 60,
      treatment: 70,
    },
    {
      name: "Kalimantan Tengah",
      confirmed: 95,
      recovered: 80,
      death: 65,
      treatment: 75,
    },
    {
      name: "Sulawesi Utara",
      confirmed: 100,
      recovered: 85,
      death: 70,
      treatment: 80,
    },
    {
      name: "Papua",
      confirmed: 105,
      recovered: 90,
      death: 75,
      treatment: 85,
    },
    {
      name: "Kalimantan Utara",
      confirmed: 110,
      recovered: 95,
      death: 80,
      treatment: 90,
    },
    {
      name: "Aceh",
      confirmed: 115,
      recovered: 100,
      death: 85,
      treatment: 95,
    },
    {
      name: "Jambi",
      confirmed: 120,
      recovered: 105,
      death: 90,
      treatment: 100,
    },
    {
      name: "Nusa Tenggara Barat",
      confirmed: 125,
      recovered: 110,
      death: 95,
      treatment: 105,
    },
    {
      name: "Papua Barat",
      confirmed: 130,
      recovered: 115,
      death: 100,
      treatment: 110,
    },
    {
      name: "Bengkulu",
      confirmed: 135,
      recovered: 120,
      death: 105,
      treatment: 115,
    },
    {
      name: "Sulawesi Tenggara",
      confirmed: 140,
      recovered: 125,
      death: 110,
      treatment: 120,
    },
    {
      name: "Maluku",
      confirmed: 145,
      recovered: 130,
      death: 115,
      treatment: 125,
    },
    {
      name: "Sulawesi Barat",
      confirmed: 150,
      recovered: 135,
      death: 120,
      treatment: 130,
    },
    {
      name: "Maluku Utara",
      confirmed: 155,
      recovered: 140,
      death: 125,
      treatment: 135,
    },
    {
      name: "Gorontalo",
      confirmed: 160,
      recovered: 145,
      death: 130,
      treatment: 140,
    },
  ],
}
export default data;